language: php
php:
  - "5.3"
  - "5.4"
  
before_script:
  - composer require --no-update satooshi/php-coveralls:dev-master
  - composer update --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
